# Generated by Django 5.0.4 on 2024-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0002_alter_profile_img_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
