# Generated by Django 5.0.4 on 2024-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0003_alter_profile_img_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, default='patient', max_length=100, null=True),
        ),
    ]
