# Generated by Django 5.0.4 on 2024-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0008_doctortype_remove_doctor_doctor_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='male', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_diseases',
            field=models.ManyToManyField(blank=True, to='ewp.previousdiseases'),
        ),
    ]
