# Generated by Django 5.0.4 on 2024-06-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0009_previousdiseases_patient_age_patient_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ewp.doctortype')),
            ],
        ),
    ]
