# Generated by Django 5.0.4 on 2024-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0010_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('doctor_type', models.CharField(max_length=255)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('treatment', models.TextField()),
                ('medication', models.TextField()),
            ],
        ),
    ]
